language: rust
rust:
  - nightly-2017-09-10
env:
  - BOX2D_INCLUDE_PATH="$TRAVIS_BUILD_DIR/lib/include"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y freeglut3-dev
  - sudo apt-get install -y libgtk-3-dev

script:
  - cargo update -p clippy
  - cargo build
