environment:
  matrix:
  - TARGET: nightly-2017-09-10-x86_64-pc-windows-msvc
install:
  - git submodule update --init --recursive
  - ps: if (ls -r . -fi "*.rs" | sls "`t") { throw "Found tab character" }
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - ps: $env:BOX2D_INCLUDE_PATH="$(pwd)\lib\include"
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build

test_script:
  - cargo test
