environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    CHANNEL: nightly-2017-09-10
install:
  - git submodule update --init --recursive
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGERT% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - ps: $env:BOX2D_INCLUDE_PATH="$(pwd)\lib\include"
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build

test_script:
  - cargo test
